### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by scheung38** [msenechal/neo4j-needle-starterkit#9]
How to connect please given created on console.neo4j.io:

neo4j+s://<INSTANCE_NAME>.databases.neo4j.io

[Screenshot 2023-11-28 at 01.59.31.pdf](https://github.com/msenechal/neo4j-needle-starterkit/files/13482541/Screenshot.2023-11-28.at.01.59.31.pdf)

Tried

Just just the instance name:<INSTANCE_NAME>
<INSTANCE_NAME>.databases.neo4j.io
neo4j+s://<INSTANCE_NAME>.databases.neo4j.io

All seem to return NOT CONNECTED

OK got it: needed username:password prefixes

But how do we proceed next as all we have now is a screen that shows CONNECTED

**Comment by msenechal** [comment]
Hi @scheung38 , Thanks for showing interests in the starter kit !
Glad to hear you were able to fixed the connection. Just out of curiosity, I'm not sure I understood this:
> OK got it: needed username:password prefixes
What prefixes and where? It should just work by putting your username/password in the user inputs

For your next comment:
> But how do we proceed next as all we have now is a screen that shows CONNECTED
This Starter Kit is only a template to build a simple React Application and show you how to connect (create a driver session) to your Neo4j Database. It is not meant as a tool or full app for exploring your data, but more for getting your started on building your app faster. So you will need to implement queries/visualisations based on your needs.
